name: Lint & build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm install --ci
    - name: Lint
      run: npm run lint
    - name: Check if project builds
      run: npm run build
